[package]
name = "rainforest_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
chargrid_wgpu = { version = "0.2", features = ["gamepad"] }
env_logger = "0.9"
rainforest_app = { path = "../app", features = ["print_stdout"] }
rainforest_native = { path = "../native" }
