[workspace]

resolver = "2" # this is required for the wgpu frontend

members = [
    "game",
    "app",
    "native",
    "ansi-terminal",
    "web",
    "ggez",
    "wgpu",
    "util/rational",
    "util/rand-range",
]

[profile.release]
lto = true
