[package]
name = "rainforest_ggez"
version = "0.1.0"
edition = "2021"

[dependencies]
gridbugs = { version = "0.2", features = [ "chargrid_ggez_gamepad" ] }
env_logger = "0.9"
rainforest_app = { path = "../app", features = ["print_stdout"] }
rainforest_native = { path = "../native" }
